###    lovelybacon.deviantart.com   ####

# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout somewhen, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# bar {
#   position top
# }

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below. ISO 10646 = Unicode
font pango:System San Francisco Display 50
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, if you need a lot of unicode glyphs or
# right-to-left text rendering, you should instead use pango for rendering and
# chose a FreeType font, such as:
 font pango:FontAwesome 8.3

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# autostart programs


exec --no-startup-id sh ~/.fehbg 
# exec --no-startup-id feh --randomize --bg-fill /mnt/data/images
exec --no-startup-id urxvtd -q -f -o
exec --no-startup-id transmission-daemon
exec --no-startup-id pcmanfm /mnt/data/downloads
exec --no-startup-id firefox
# exec --no-startup-id urxvtc


# start a terminal
bindsym $mod+Return exec urxvt -depth 32 -bg rgba:3f00/3f00/3f00/dddd


# start programs
bindsym $mod+b exec --no-startup-id lmms
bindsym $mod+m exec --no-startup-id geary
bindsym $mod+p exec --no-startup-id pcmanfm /mnt/data/downloads
bindsym $mod+f  exec --no-startup-id firefox
bindsym $mod+g exec --no-startup-id gimp
bindsym $mod+o exec --no-startup-id gpodder
#bindsym $mod+l  exec --no-startup-id medit
#bindsym $mod+k  exec --no-startup-id gcolor2
bindsym $mod+shift+v  exec --no-startup-id virtualbox
bindsym $mod+shift+F1 exec --no-startup-id scrot -q 100 -c -d 2 "/mnt/data/firefox/Scrot_%Y-%m-%d_%H:%M:%S.png"
bindsym $mod+shift+F3 exec --no-startup-id leafpad ~/.i3/config
bindsym $mod+shift+p exec --no-startup-id lxappearance
bindsym F12 exec --no-startup-id feh --hide-pointer -x -q -D 10 -B black -F -z /mnt/data/images

# kill focused window
bindsym $mod+q kill

# start dmenu (a program launcher)
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
bindsym $mod+d exec rofi -show run -lines 3 -eh 2 -width 100 -padding 475 -opacity "85" -bw 0 -bc "#2f343f" -bg "$bg-color" -fg "$text-color" -hlbg "$bg-color" -hlfg "#9575cd"
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
#bindsym $mod+Left focus left
#bindsym $mod+Down focus down
#bindsym $mod+Up focus up
#bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+c split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+x fullscreen

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child


# customize workspace names
# set $ws1 1 urxvt
# set $ws2 2 pcmanfm
# set $ws3 3 firefox
# set $ws4 4 video
# set $ws5 5 edit


# switch to workspace3
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# border / titlebar
new_window normal
hide_edge_borders vertical
bindsym Control+Shift+x [class="^.*"] border toggle
for_window [class="^.*"] border pixel 1
for_window [class="URxvt"] border pixel 1
for_window [class="Leafpad"] border normal
for_window [class="Lxappearance"] border normal
for_window [class="Vlc"] border pixel 0
for_window [class="mpv"] border pixel 0
for_window [class="Pcmanfm"] border pixel 0
for_window [class="Firefox"] border pixel 0
for_window [class="Geary"] border pixel 0
for_window [class="Lmms"] border pixel 0
for_window [class="Feh"] border pixel 0


# reload the configuration file
bindsym $mod+Shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec i3-msg exit

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 5 px or 5 ppt
        bindsym k resize grow height 5 px or 5 ppt
        bindsym l resize shrink height 5 px or 5 ppt
        bindsym k resize grow width 5 px or 5 ppt

        # same bindings, but for the arrow keys
        bindsym Right resize shrink width 5 px or 5 ppt
        bindsym Down resize grow height 5 px or 5 ppt
        bindsym Up resize shrink height 5 px or 5 ppt
        bindsym Left resize grow width 5 px or 5 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

set $bg-color            #2f343f
set $inactive-bg-color   #2f343f
set $text-color          #676E7D
set $inactive-text-color #676E7D
set $urgent-bg-color     #E53935

# window colors
#                       border              background         text                 indicator
client.focused          $bg-color           $bg-color          $text-color          #00ff00
client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color #00ff00
client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color #00ff00
client.urgent           $urgent-bg-color    $urgent-bg-color   $text-color          #00ff00


# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)

bar {
    status_command conky -c $HOME/.config/i3/conky/conkyrc
    mode dock
    position bottom 
    font pango:open sans 12
    strip_workspace_numbers yes
colors {
        background #DEDFE3
        statusline #767E8A
        separator #51c4d4

        focused_workspace  #777F8B #777F8B #ecedee
        active_workspace   #777F8B #777F8B #ecedee
        inactive_workspace #DEDFE3 #DEDFE3 #767E8A
        urgent_workspace   #DEDFE3 #DEDFE3 #767E8A
    }
}





#################################################################################################################################


#assign [class="Pcmanfm"] 2 pcmanfm
#assign [class="Lxappearance"] 2 pcmanfm
#assign [class="mpv"] 4 video
#assign [class="Gnome-mplayer"] 4 video
#assign [class="MPlayer"] 4 video
#assign [class="medit"] 5 edit
#assign [class="Audacity"] 5 edit
#assign [class="Audacious"] 5 edit
#assign [class="Nitrogen"] 5 edit
# assign [class="Gcolor2"] 5 edit
#assign [class="Evince"] 5 edit
#assign [class="Geary"] 5 edit
#assign [class="Lmms"] 5 edit
#assign [class="Gimp"] 6 xb
#assign [class="VirtualBox"] 6 xb
#assign [class="GParted"] 6 xb
#assign [class="Gpodder"] 6 xb
#assign [class="Rawtherapee"] 6 xb


# switching between workspace
# http://i3wm.org/docs/userguide.html#_changing_named_workspaces_moving_to_workspaces
bindsym $mod+period workspace next
bindsym $mod+comma workspace prev 

# xmodmap ~/.Xmodmap &

bindsym XF86AudioRaiseVolume exec --no-startup-id amixer set -c 0 Master 2%+
bindsym XF86AudioLowerVolume exec --no-startup-id amixer set -c 0 Master 2%-

bindsym Shift+XF86AudioRaiseVolume exec --no-startup-id amixer -c 0 set Master 15%+
bindsym Shift+XF86AudioLowerVolume exec --no-startup-id amixer -c 0 set Master 15%-

bindsym XF86AudioMute exec amixer -c 0 -q set Master toggle

bindsym XF86MonBrightnessDown exec xbacklight -5

bindsym XF86MonBrightnessUp exec xbacklight +5


##  bindsym $MOD+SHIFT+x exec i3lock -i /mnt/data/images/1b3a047dd12ba1db51192a95781be456.jpg
bindsym $MOD+SHIFT+x exec i3lock -c 000000

exec_always xmodmap -e "clear lock" #disable caps lock switch
exec_always xmodmap -e "keysym Caps_Lock = Escape" #set caps_lock as escape

exec --no-startup-id compton -f --config $HOME/.config/compton/config
